version: '3.8'

services:
  product-api-mock:
    build:
      context: ./product-api-mock
    image: product-api-mock
    restart: always
    volumes:
      - ./product-api-mock:/product-api-mock
    ports:
      - 8081:8081
