version: '3.8'

services:
  product-api-mock:
    image: clue/json-server
    container_name: product-api-mock
    ports:
      - '8081:80'
    volumes:
      - ./product-api-mock/products.json:/data/db.json
